### PR TITLE
Update for MuseScore 4.0(.1)

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Should work especially well together with https://github.com/musescore/MuseScore/pull/15687, which contains some more fixes on the MuseScore side.

### CODE REVIEW

**Comment by jgadsden** [comment]
Many thanks @cbjeukendrup , this is great to see
I am travelling until Monday to Wednesday this week, so I will be able to review it for you on Thursday 5th (maybe earlier) id that is OK with you?

**Comment by cbjeukendrup** [comment]
Yes, that's fine!

**Comment by jgadsden** [comment]
Thanks @cbjeukendrup for this - I have added the category code so that it appears in the plugins drop-down menu.
I was a bit slow in approving, I took some time looking at the new MuseScore 4.0 release ... good to see these improvements, thank you

**Review by jgadsden — APPROVED** [review]
Thanks @cbjeukendrup , I have added a category code and a title so that it is easier to use in MuseScore 4. I will go ahead and merge

**Pull request merged**
